# Generated by Django 4.2 on 2023-04-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='user_id',
            new_name='user',
        ),
    ]
